-- 코드를 입력하세요
SELECT T1.HOUR, COUNT(*) AS COUNT
FROM (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
    FROM ANIMAL_OUTS
) T1
WHERE T1.HOUR BETWEEN 9 AND 19
GROUP BY T1.HOUR
ORDER BY T1.HOUR;