-- 코드를 작성해주세요
SELECT T2.SCORE, T1.EMP_NO, T1.EMP_NAME, T1.POSITION, T1.EMAIL
FROM HR_EMPLOYEES T1
    JOIN
    (SELECT 
        EMP_NO, 
        SUM(SCORE) AS SCORE,
        RANK() OVER (ORDER BY SUM(SCORE) DESC) AS SCORE_RANK
    FROM HR_GRADE
    GROUP BY EMP_NO) T2 ON T1.EMP_NO = T2.EMP_NO
WHERE T2.SCORE_RANK = 1;
                            


