-- 코드를 작성해주세요 
SELECT
    EXTRACT(YEAR FROM T1.DIFFERENTIATION_DATE) AS YEAR,
    (T2.COLONY - T1.SIZE_OF_COLONY) AS YEAR_DEV,
    T1.ID
FROM ECOLI_DATA AS T1
JOIN (
    SELECT
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS T2
ON EXTRACT(YEAR FROM T1.DIFFERENTIATION_DATE) = T2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;
